import { Overpass } from "next/font/google"
import QueryWrapper from "./auth/QueryWrapper"
import Nav from "./components/Nav"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const overpass = Overpass({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-overpass",
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`mx-2 sm:mx-5 md:mx-28 lg:mx-60 xl:mx-80  bg-zinc-800`}>
        <Nav />
        <QueryWrapper>{children}</QueryWrapper>
      </body>
    </html>
  )
}
